name: 'Load docker image from github artifact'
description: 'Downloads an artifact from ./.github/actions/build-docker and loads to docker images'
inputs:
  artifact_name:
    required: true
    description: "The name of the uploaded artifact"
  target:
    required: true
    description: "Which target of the docker image to load?"

runs:
  using: 'composite'
  steps:
    - name: Download dir
      id: download
      shell: bash
      run: |
        echo "path=/tmp/load-docker" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@v4
      with:
        # We expect the image to be uploaded with the image digest
        name: ${{ inputs.artifact_name }}
        path: ${{ steps.download.outputs.path }}

    - name: Load image
      shell: bash
      run: |
        tmp_dir="${{ steps.download.outputs.path }}"
        ls -lan $tmp_dir

        docker load < "$tmp_dir/${{ inputs.target }}"
