name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push the image to registry?'
        default: "false"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.push }}
  cancel-in-progress: true

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build container
        id: build_container
        uses: ./.github/actions/build-docker
        with:
          push: ${{ inputs.push }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
