name: Build Docker image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.push }}
  cancel-in-progress: true

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build container
        id: build_container
        uses: ./.github/actions/build-docker
